#pragma once
#define _USE_MATH_DEFINES
#include <algorithm>
#include <array>
#include <assert.h>
#include <cmath>
#include <functional>
#include <math.h>
#include <memory>
#include <random>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>
#include <SFML/Graphics/Color.hpp>
#include "vector.h"
#include "yaml.h"